version: '3.7'

services:

  php-fpm:
    build: ./php
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '80:80'
    volumes:
      - ./:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

